platform :ios, '15.0'

target 'ALISASDKUIKitExample' do
  use_frameworks!

end

target 'ALISASDKUIKitExampleTests' do
  inherit! :search_paths
end

target 'ALISASDKUIKitExampleUITests' do
  inherit! :search_paths
end
