platform :ios, '15.0'

source 'https://github.com/Ali-Corp/PodSpecs.git'
source 'https://cdn.cocoapods.org/'

target 'ALISASDKUIKitExample' do
  use_frameworks!

  pod 'AliSASDK', :git => 'https://github.com/Ali-Corp/AliSASDK.git', :tag => '1.0.1'
end

target 'ALISASDKUIKitExampleTests' do
  inherit! :search_paths
end

target 'ALISASDKUIKitExampleUITests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end

    aggregate_target.user_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end

    aggregate_target.user_project.save
  end
end
