platform :ios, '15.0'

source 'https://github.com/Ali-Corp/PodSpecs.git'
source 'https://cdn.cocoapods.org/'

target 'ALISASDKSwiftUIExample' do
  use_frameworks!

  pod 'AliSASDK', :git => 'https://github.com/Ali-Corp/AliSASDK.git', :tag => '1.0.1'
end

target 'ALISASDKSwiftUIExampleTests' do
  inherit! :search_paths
end

target 'ALISASDKSwiftUIExampleUITests' do
  inherit! :search_paths
end
