platform :ios, '15.0'

target 'ALISASDKSwiftUIExample' do
  use_frameworks!

end

target 'ALISASDKSwiftUIExampleTests' do
  inherit! :search_paths
end

target 'ALISASDKSwiftUIExampleUITests' do
  inherit! :search_paths
end
